name: PR Preview Label Handler

on:
  pull_request:
    types:
      - labeled

jobs:
  handle-pr-preview:
    if: contains(github.event.label.name, 'pr-preview-')
    runs-on: ubuntu-latest

    steps:
      - name: Extract Service and PR Number
        id: extract
        run: |
          echo "::set-output name=service::${{ github.event.label.name#pr-preview- }}"
          echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

      - name: Log Information
        run: |
          echo "Service: ${{ steps.extract.outputs.service }}"
          echo "PR Number: ${{ steps.extract.outputs.pr_number }}"

      - name: Add Preview Ready Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: preview-ready-${{ steps.extract.outputs.service }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
