name: PR Preview Label Handler

on:
  pull_request:
    types:
      - labeled

jobs:
  handle-pr-preview:
    if: startsWith(github.event.label.name, 'pr-preview-')
    runs-on: ubuntu-latest

    steps:
      - name: Extract Service and PR Number
        id: extract
        run: |
          label="${{ github.event.label.name }}"
          service=$(echo "$label" | sed 's/^pr-preview-//')
          echo "Extracted service: $service"
          echo "service=$service" >> $GITHUB_ENV
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Log Information
        run: |
          echo "Service: ${{ env.service }}"
          echo "PR Number: ${{ env.pr_number }}"

      - name: Add Preview Ready Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: preview-ready-${{ env.service }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
