name: PR Preview Label Handler

on:
  pull_request:
    types:
      - labeled

jobs:
  handle-pr-preview:
    if: startsWith(github.event.label.name, 'pr-preview-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Service and PR Number
        id: extract
        run: |
          label="${{ github.event.label.name }}"
          service=$(echo "$label" | sed 's/^pr-preview-//')
          echo "Extracted service: $service"
          echo "service=$service" >> $GITHUB_ENV

      - name: Log Information
        run: |
          echo "Service: ${{ env.service }}"
          echo "PR Number: ${{ env.pr_number }}"

      - name: Trigger initialize-preview action
        uses: ./actions/initialize-preview
        with:
          service_name: ${{ env.service }}"
          pr_number: ${{ github.event.pull_request.number }}

      - name: Add Preview Ready Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: preview-ready-${{ env.service }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine deployment link based on service
        run: |
          if [ "$service" = "starkgate-v2" ]; then
            link="mostar2.${{ github.event.pull_request.number }}.sw-dev.io"
          elif [ "$service" = "ofir" ]; then
            link="mostar2.${{ github.event.pull_request.number }}.sw-dev.io"
          else
            echo "Service not supported"
            exit 1

          fi
          echo "link=${link}" >> $GITHUB_ENV

      - name: Add Preview Initialized Comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          body: |
            PR preview has deployed successfully! Link: ${{ env.link }}
