name: On StarkGate tag push

on:
  push:
    tags:
      - "@starkgate*/*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to push"
        required: true

jobs:
  starkgate-release-argo:
    name: Build image and release to Dev
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.inputs.tag || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.7.0
          run_install: false

      - name: Install versioning tool dependencies
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm --filter @pipeline/tag-extractor install
          pnpm --filter @pipeline/tag-extractor build
          cp ./workspace/pipeline/tag-extractor/dist/index.js ./actions/common/tag-extractor

      - name: Extract tag properties
        id: properties
        uses: ./actions/common/tag-extractor
        with:
          tag: ${{ github.event.inputs.tag || github.ref_name }}

      - name: Determine Version Subpath
        shell: bash
        run: |
          if [[ "${{ steps.properties.outputs.service_version_suffix }}" != "" ]]; then
            echo "version_sub_path=/${{ steps.properties.outputs.service_version_suffix }}" >> $GITHUB_OUTPUT
          else
            echo "version_sub_path=" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Image Dev
        uses: ./actions/starkgate/build-image
        with:
          service: ${{ steps.properties.outputs.service }}
          app: ${{ steps.properties.outputs.app }}
          version: ${{ steps.properties.outputs.version }}
          label: latest
          type: ${{ steps.properties.outputs.type }}
          gcp_project: starkgate-dev
          gcp_token: ${{ secrets.gcp_token_starkgate_dev }}
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          prerelease: ${{ steps.properties.outputs.prerelease }}
          version_sub_path: ${{ steps.properties.outputs.version_sub_path }}
