name: PR Labelled Preview

on:
  pull_request:
    types: [labeled]

jobs:
  preview:
    if: contains(github.event.label.name, 'pr-preview-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.7.0
          run_install: false

      - name: Extract Service Secrets
        id: extract-secrets
        env:
          SERVICE_NAME: ${{ github.event.label.name.replace('pr-preview-', '') }}
        run: |
          # Path to the deployment-config JSON files
          CONFIG_PATH="./deployment-config"
          CONFIG_FILE="$CONFIG_PATH/${SERVICE_NAME}.deployment-config.json"
          echo "Using configuration file: $CONFIG_FILE"
          # Check if the configuration file exists
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Error: Configuration file $CONFIG_FILE not found."
            exit 1
          fi

          # Extract the secrets array from the JSON file
          SECRETS=$(jq -r '.secrets[]' "$CONFIG_FILE")

          # Export each secret as an environment variable
          for SECRET in $SECRETS; do
            if [ -z "${{ secrets[$SECRET] }}" ]; then
              echo "Error: Secret $SECRET is not defined in GitHub repository secrets."
              exit 1
            fi
            echo "$SECRET=${{ secrets[$SECRET] }}" >> $GITHUB_ENV
          done

      - name: Log environment variables
        run: |
          node -e "
          Object.entries(process.env).forEach(([key, value]) => {
            console.log(\`\${key}: \${value}\`);
          });
          "
